Repository parseablehq/console, pull requests merged in 2025-01, with the labels that each got.

#404 Fix: Edit Tile Modal Dashboards
  src/pages/Dashboards/CreateTileForm.tsx
  src/pages/Stream/providers/FilterProvider.tsx
Labels: frontend, Ready to merge, console, console/dashboard

#405 Limit Filter builder rules
  src/pages/Stream/components/Querier/FilterQueryBuilder.tsx
Labels: Ready to merge, console

#403 Removed Caching from console
  src/@types/parseable/api/about.ts
  src/@types/parseable/api/clusterInfo.ts
  src/@types/parseable/api/stream.ts
  src/api/caching.ts
  src/api/constants.ts
  src/components/Navbar/infoModal.tsx
  src/hooks/useCacheToggle.tsx
  src/pages/Stream/providers/StreamProvider.tsx
  src/pages/Systems/MachineInfo.tsx
Labels: Ready to merge, console

#407 fix: Fixed empty stream loading state
  src/hooks/useGetStreamMetadata.ts
  tests/home.spec.ts
Labels: bug, console/home

#408 fix: Column filter cas sensitive fix
  src/pages/Stream/components/Column.tsx
Labels: bug, console/explore

#409 fix: Column list scroll issue & Row actions btn fix
  src/pages/Stream/Views/Explore/LogsViewConfig.tsx
  src/pages/Stream/Views/Explore/StaticLogTable.tsx
Labels: bug, console/explore

#410 Deprecate Trino Support
  src/@types/parseable/api/about.ts
  src/@types/parseable/api/query.ts
  src/api/query.ts
  src/hooks/useQueryLogs.ts
  src/hooks/useQueryResult.tsx
  src/pages/Stream/components/EventTimeLineGraph.tsx
  src/pages/Stream/components/Querier/QueryCodeEditor.tsx
  src/pages/Stream/components/Querier/SavedFiltersModal.tsx
  src/pages/Stream/components/Querier/index.tsx
  src/pages/Stream/index.tsx
  src/pages/Stream/providers/FilterProvider.tsx
  src/utils/queryBuilder.ts
Labels: enhancement, Ready to merge, console

#406 fix: Retry on error should show success data
  src/hooks/useQueryLogs.ts
  src/pages/Stream/Views/Explore/JSONView.tsx
  src/pages/Stream/Views/Explore/LogsView.tsx
  src/pages/Stream/Views/Explore/StaticLogTable.tsx
  src/pages/Stream/Views/Explore/useLogsFetcher.ts
Labels: bug, Ready to merge, console, console/explore

#414 Fix Build
  src/hooks/useQueryLogs.ts
Labels: bug, Ready to merge, console

#416 Updated Logos
  public/favicon.ico
  src/assets/customLoader/ParseableAnimate.tsx
  src/assets/images/brand/icon.svg
  src/assets/images/brand/loadingIcon.svg
  src/assets/images/brand/logo-invert.svg
  src/assets/images/brand/logo.svg
Labels: Ready to merge, console

#415 fix: Line SHare HTTP Secure condition removed
  src/pages/Stream/Views/Explore/StaticLogTable.tsx
Labels: bug, Ready to merge, console/explore

#394 feat: Correlation feature
  src/api/query.ts
  src/assets/images/correlation_placeholder.svg
  src/components/Navbar/components/CorrelationIcon.tsx
  src/components/Navbar/index.tsx
  src/constants/routes.ts
  src/hooks/useCorrelationQueryLogs.tsx
  src/hooks/useFetchStreamData.tsx
  src/hooks/useGetCorrelationStreamSchema.ts
  src/pages/Correlation/Views/CorrelationFooter.tsx
  src/pages/Correlation/Views/CorrelationTable.tsx
  src/pages/Correlation/components/CorrelationEmptyPlaceholder.tsx
  src/pages/Correlation/components/CorrelationFieldItem.tsx
  src/pages/Correlation/components/CorrelationFilters/index.tsx
  src/pages/Correlation/components/MultiEventTimeLineGraph.tsx
  src/pages/Correlation/components/ShareButton.tsx
  src/pages/Correlation/components/StreamSelectBox.tsx
  src/pages/Correlation/index.tsx
  src/pages/Correlation/providers/CorrelationProvider.tsx
  src/pages/Correlation/styles/Correlation.module.css
  src/pages/Correlation/styles/CorrelationFilters.module.css
  src/pages/Correlation/styles/CorrelationLogs.module.css
  src/pages/Correlation/styles/Footer.module.css
  src/pages/Stream/components/PrimaryToolbar.tsx
  src/routes/elements.tsx
  src/routes/index.tsx
  src/utils/queryBuilder.ts
Labels: enhancement, console, console/correlation

#420 Deprecate Message on alerts for standalone
  src/pages/Stream/Views/Manage/Alerts.tsx
Labels: Ready to merge, console, console/manage

#413 SQL Modal Changes
  src/pages/Stream/Views/Explore/useLogsFetcher.ts
  src/pages/Stream/components/Querier/FilterQueryBuilder.tsx
  src/pages/Stream/components/Querier/index.tsx
Labels: bug, Ready to merge, console, console/explore

#412 feat: Toggle Upgrade btn based on Enterprise license
  src/@types/parseable/api/about.ts
  src/components/Header/PrimaryHeader.tsx
  src/components/Navbar/infoModal.tsx
  src/constants/index.ts
Labels: console

#421 live tail hidden
  src/constants/routes.ts
  src/pages/Stream/components/Sidebar.tsx
  src/pages/Stream/index.tsx
Labels: Ready to merge, console, console/manage

#418 Redux/setup
  package.json
  pnpm-lock.yaml
  src/main.tsx
  src/store/alertsSlice.ts
  src/store/index.ts
Labels: enhancement, Ready to merge, console

#422 Moved graph query to /datebin
  src/@types/parseable/api/query.ts
  src/api/constants.ts
  src/api/query.ts
  src/hooks/useQueryResult.tsx
  src/pages/Correlation/components/MultiEventTimeLineGraph.tsx
  src/pages/Stream/components/EventTimeLineGraph.tsx
Labels: console

#419 feat: Making JSON view as default view
  src/pages/Stream/Views/Explore/JSONView.tsx
  src/pages/Stream/components/PrimaryToolbar.tsx
  src/pages/Stream/providers/LogsProvider.tsx
  src/pages/Stream/styles/JSONView.module.css
  src/pages/Stream/utils.ts
Labels: console, console/explore

#423 Footer count render independent of logs table
  src/hooks/useQueryResult.tsx
  src/pages/Stream/Views/Explore/Footer.tsx
  src/pages/Stream/Views/Explore/useLogsFetcher.ts
Labels: Ready to merge, console/explore

#417 Correlation CRUD operations
  src/@types/parseable/api/correlation.ts
  src/api/constants.ts
  src/api/correlations.ts
  src/hooks/useCorrelationQueryLogs.tsx
  src/hooks/useCorrelations.tsx
  src/hooks/useFetchStreamData.tsx
  src/hooks/useGetCorrelationStreamSchema.ts
  src/pages/Correlation/components/MultiEventTimeLineGraph.tsx
  src/pages/Correlation/components/SaveCorrelationModal.tsx
  src/pages/Correlation/components/SavedCorrelationItem.tsx
  src/pages/Correlation/components/SavedCorrelationsBtn.tsx
  src/pages/Correlation/components/SavedCorrelationsModal.tsx
  src/pages/Correlation/hooks/useParamsController.ts
  src/pages/Correlation/index.tsx
  src/pages/Correlation/providers/CorrelationProvider.tsx
  src/pages/Correlation/styles/SaveCorrelationModal.module.css
  src/pages/Correlation/styles/SavedCorrelationItem.module.css
  src/pages/Correlation/styles/SavedCorrelationsBtn.module.css
  src/pages/Correlation/utils.ts
Labels: enhancement, console/correlation

#431 fix: Removed /info call dependancy from explore page
  src/pages/Stream/Views/Explore/useLogsFetcher.ts
  src/pages/Stream/Views/Manage/Info.tsx
  src/pages/Stream/Views/Manage/Management.tsx
  src/pages/Stream/components/EventTimeLineGraph.tsx
  src/pages/Stream/index.tsx
Labels: console/explore, for release

#432 fix: Filters dropdown text fix in case of undefined
  src/pages/Stream/components/Querier/FilterQueryBuilder.tsx
Labels: bug, console/explore, for release

#434 Esc key press to close querier modal
  src/pages/Stream/components/Querier/index.tsx
Labels: bug, Ready to merge, console/explore, for release

#429 hot tier refresh
  src/hooks/useHotTier.ts
  src/pages/Stream/Views/Manage/Management.tsx
  src/pages/Stream/Views/Manage/Settings.tsx
Labels: enhancement, console/manage, for release

#430 fix: Page crash on navigating to /explore from manage page
  src/pages/Stream/hooks/useParamsController.ts
Labels: bug, console, for release

#437 fix: Font size fixes on explore & correlation page
  src/components/Header/RefreshInterval.tsx
  src/components/Header/RefreshNow.tsx
  src/components/Header/ShareButton.tsx
  src/components/Header/TimeRange.tsx
  src/components/Header/styles/LogQuery.module.css
  src/pages/Correlation/styles/SavedCorrelationsBtn.module.css
  src/pages/Stream/components/PrimaryToolbar.tsx
  src/pages/Stream/components/Querier/index.tsx
  src/pages/Stream/components/styles/PrimaryToolbar.module.css
Labels: bug, console/explore

#436 fix: Detect schema JSON type fix
  src/hooks/useLogStream.tsx
  src/pages/Home/CreateStreamModal.tsx
Labels: bug

#435 fix: JSON view CSS fixes
  src/pages/Stream/Views/Explore/JSONView.tsx
  src/pages/Stream/styles/JSONView.module.css
Labels: bug, for release
